/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OsRouteImport } from './routes/_os'
import { Route as OsIndexRouteImport } from './routes/_os/index'
import { Route as OsAppRouteImport } from './routes/_os/$app'
import { Route as ApiPhotosIdRouteImport } from './routes/api/photos.$id'

const OsRoute = OsRouteImport.update({
  id: '/_os',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIndexRoute = OsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OsRoute,
} as any)
const OsAppRoute = OsAppRouteImport.update({
  id: '/$app',
  path: '/$app',
  getParentRoute: () => OsRoute,
} as any)
const ApiPhotosIdRoute = ApiPhotosIdRouteImport.update({
  id: '/api/photos/$id',
  path: '/api/photos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof OsIndexRoute
  '/$app': typeof OsAppRoute
  '/api/photos/$id': typeof ApiPhotosIdRoute
}
export interface FileRoutesByTo {
  '/$app': typeof OsAppRoute
  '/': typeof OsIndexRoute
  '/api/photos/$id': typeof ApiPhotosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_os': typeof OsRouteWithChildren
  '/_os/$app': typeof OsAppRoute
  '/_os/': typeof OsIndexRoute
  '/api/photos/$id': typeof ApiPhotosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$app' | '/api/photos/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/$app' | '/' | '/api/photos/$id'
  id: '__root__' | '/_os' | '/_os/$app' | '/_os/' | '/api/photos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OsRoute: typeof OsRouteWithChildren
  ApiPhotosIdRoute: typeof ApiPhotosIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_os': {
      id: '/_os'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_os/': {
      id: '/_os/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OsIndexRouteImport
      parentRoute: typeof OsRoute
    }
    '/_os/$app': {
      id: '/_os/$app'
      path: '/$app'
      fullPath: '/$app'
      preLoaderRoute: typeof OsAppRouteImport
      parentRoute: typeof OsRoute
    }
    '/api/photos/$id': {
      id: '/api/photos/$id'
      path: '/api/photos/$id'
      fullPath: '/api/photos/$id'
      preLoaderRoute: typeof ApiPhotosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OsRouteChildren {
  OsAppRoute: typeof OsAppRoute
  OsIndexRoute: typeof OsIndexRoute
}

const OsRouteChildren: OsRouteChildren = {
  OsAppRoute: OsAppRoute,
  OsIndexRoute: OsIndexRoute,
}

const OsRouteWithChildren = OsRoute._addFileChildren(OsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  OsRoute: OsRouteWithChildren,
  ApiPhotosIdRoute: ApiPhotosIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
